#!/bin/sh

cd "$HOME"

echo "Init submodules"
yadm submodule update --recursive --init

if [ $(uname -a | grep -c "Darwin") -ne 0 ]; then
  brew bundle --file=~/.config/yadm/Brewfile
fi

if [ $(uname -a | grep -c "arch-linux") -ne 0 ]; then
  yay -S --needed --noconfirm - < ~/.config/yadm/yay-list.txt
fi
